"""initial schema

Revision ID: 49da4b9e0f47
Revises: 
Create Date: 2026-08-11 00:29:36.728602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49da4b9e0f47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('analysis_projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('species', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'COMPLETED', name='project_status_enum'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_projects_owner_id'), 'analysis_projects', ['owner_id'], unique=False)
    op.create_table('environmental_readings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('salinity_psu', sa.Float(), nullable=True),
    sa.Column('light_intensity_umol_m2_s', sa.Float(), nullable=True),
    sa.Column('dissolved_oxygen_mg_l', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['analysis_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_readings_project_id'), 'environmental_readings', ['project_id'], unique=False)
    op.create_index(op.f('ix_environmental_readings_recorded_at'), 'environmental_readings', ['recorded_at'], unique=False)
    op.create_table('microalgae_images',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processing_status_enum'), nullable=False),
    sa.Column('processing_error', sa.String(length=2000), nullable=True),
    sa.Column('cell_count', sa.Integer(), nullable=True),
    sa.Column('avg_cell_diameter_um', sa.Float(), nullable=True),
    sa.Column('std_cell_diameter_um', sa.Float(), nullable=True),
    sa.Column('cell_density_cells_per_ml', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extra_metrics', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['analysis_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_microalgae_images_processing_status'), 'microalgae_images', ['processing_status'], unique=False)
    op.create_index(op.f('ix_microalgae_images_project_id'), 'microalgae_images', ['project_id'], unique=False)
    op.create_table('trend_estimates',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.Enum('CELL_COUNT', 'AVG_CELL_SIZE', 'CELL_DENSITY', name='trend_metric_enum'), nullable=False),
    sa.Column('direction', sa.Enum('INCREASING', 'DECREASING', 'STABLE', 'INSUFFICIENT_DATA', name='trend_direction_enum'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_start', sa.Float(), nullable=True),
    sa.Column('value_end', sa.Float(), nullable=True),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['analysis_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_estimates_project_id'), 'trend_estimates', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_estimates_project_id'), table_name='trend_estimates')
    op.drop_table('trend_estimates')
    op.drop_index(op.f('ix_microalgae_images_project_id'), table_name='microalgae_images')
    op.drop_index(op.f('ix_microalgae_images_processing_status'), table_name='microalgae_images')
    op.drop_table('microalgae_images')
    op.drop_index(op.f('ix_environmental_readings_recorded_at'), table_name='environmental_readings')
    op.drop_index(op.f('ix_environmental_readings_project_id'), table_name='environmental_readings')
    op.drop_table('environmental_readings')
    op.drop_index(op.f('ix_analysis_projects_owner_id'), table_name='analysis_projects')
    op.drop_table('analysis_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
